[build]
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# --- Nagłówki ---
[[headers]]
  for = "/*"
  [headers.values]
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"