[build]
  command = "npm run build"
  # Wracamy do tego, co najprawdopodobniej generuje Twój build
  publish = "dist/public"

# --- Przekierowania (pozostają bez zmian, skonsolidowane tutaj) ---
[[redirects]]
  from = "https://www.blackhole-universe.netlify.app/*"
  to = "https://blackhole-universe.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# --- Nagłówki (pozostają bez zmian) ---
[[headers]]
  for = "/*"
  [headers.values]
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"